package posbackend;

import java.awt.BorderLayout;

public class MainFrame extends javax.swing.JFrame {
    
    private SignInPanel signInPanel;
    private OptionsPanel optionsPanel;
    private NewOrderPanel newOrderPanel;
    private ClockInOutPanel clockInOutPanel;
    private ManagerPanel managerPanel;
    private ViewOrdersPanel viewOrdersPanel;
    private POSbackend posBackEnd;
    
    public MainFrame() {
        initComponents();
        posBackEnd = new POSbackend();
        posBackEnd.start();
        signInPanel = new SignInPanel();
        this.signInPanel.setMainFrame(this);
        this.getContentPane().add(this.signInPanel, BorderLayout.CENTER);
    }

    public void signInUser(){
        this.getContentPane().remove(this.signInPanel);
        this.optionsPanel = new OptionsPanel();
        this.optionsPanel.setMainFrame(this);
        this.getContentPane().add(this.optionsPanel, BorderLayout.CENTER);
        this.validate();
        this.repaint();
    }
    
    public void newOrder(){
        this.getContentPane().remove(this.optionsPanel);
        this.newOrderPanel = new NewOrderPanel();
        this.newOrderPanel.setMainFrame(this);
        this.getContentPane().add(this.newOrderPanel, BorderLayout.CENTER);
        this.validate();
        this.repaint();
    }
    
    public void clockInOut(){
        this.getContentPane().remove(this.optionsPanel);
        this.clockInOutPanel = new ClockInOutPanel();
        this.clockInOutPanel.setMainFrame(this);
        this.getContentPane().add(this.clockInOutPanel, BorderLayout.CENTER);
        this.validate();
        this.repaint();
    }
    
    public void manager(){
        this.getContentPane().remove(this.optionsPanel);
        this.managerPanel = new ManagerPanel();
        this.managerPanel.setMainFrame(this);
        this.getContentPane().add(this.managerPanel, BorderLayout.CENTER);
        this.validate();
        this.repaint();
    }
    
    public void viewOrders(){
        this.getContentPane().remove(this.optionsPanel);
        this.viewOrdersPanel = new ViewOrdersPanel();
        this.viewOrdersPanel.setMainFrame(this);
        this.getContentPane().add(this.viewOrdersPanel, BorderLayout.CENTER);
        this.validate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 800));
        setResizable(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
